##application.ymlæ ¼å¼æ˜¯å¯¹propertiesçš„ç®€åŒ–

##é…ç½®jspè§£æ
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp


##MySQLè¿æ¥
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: zhangqi1112
#    url: jdbc:mysql://127.0.0.1/orderonwechat?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
#
#
#
##æ‰“å°æ—¥å¿—
##logging:
##  #æ ¼å¼åŒ–
##  pattern:
##    console: "%d ğŸ’— - %msg%n"
##    #è®¾ç½®æ—¥å¿—çº§åˆ« ä¸‹é¢ä¸¾ä¾‹ä»é«˜çº§åˆ«åˆ°ä½çº§åˆ«
###    ERROR(40, "ERROR"),
###    WARN(30, "WARN"),
###    INFO(20, "INFO"),
###    DEBUG(10, "DEBUG"),
###    TRACE(0, "TRACE");
##    level: debug
##  #è®¾ç½®æ—¥å¿—è¾“å‡ºè·¯å¾„,é»˜è®¤ä¸ºspring.log
##  #path: E:\
##  #è®¾ç½®æ–‡ä»¶åç§°
##  file: E:\orderOnWeChat.log
##
##  #è®¾ç½®æ—¥å¿—çº§åˆ«åˆ°æŸä¸ªç±»
##  #level:
##    #com.ykmimi.newindex.LoggerTest: debug